name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"

categories:
  - title: Breaking Changes
    labels: [breaking]
  - title: Features
    labels: [feat]
  - title: Bug Fixes
    labels: [fix]
  - title: Refactoring
    labels: [refactor]
  - title: Documentation
    labels: [docs]
  - title: Testing
    labels: [test]
  - title: Build
    labels: [build]

version-resolver:
  minor:
    labels: [breaking]
  default: patch

template: |
  $CHANGES
change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&@'
no-changes-template: "No changes"
category-template: "### $TITLE"

exclude-labels:
  - release

replacers:
  - search: '/- (feat|fix|refactor|docs|ci|chore|test|build|release)(\(.+?\))?!?:\s*/g'
    replace: "- "
