name: Project Board Automation

on:
  issues:
    types: [labeled]
  create:

jobs:
  automation:
    uses: medmodels/action-templates/.github/workflows/project-board-automation.yml@main
    with:
      project-number: 4
      add-trigger: accepted-label
    secrets:
      project-token: ${{ secrets.PROJECT_TOKEN }}
